### PR TITLE
Update optimac.sh

### PR DESCRIPTION
**Pull request by ajwdd**
Addition of cache clearing along with further unnecessary telemetry blocking.

### CODE REVIEW

**Comment by ajwdd** [comment]
Also, please let me know of any other additions you'd like to make. I am working on safely removing preinstalled apps without bricking the OS.

**Comment by levi-chavez** [comment]
Thanks for the addition! I personally have never removed preinstalled apps without bricking my OS. It was super easy on Mojave and lower, and now you need to do more than just mount your drive as read/write. Thats coming from a Linux daily driver with a Mac on the side, I'm by no means scared of the terminal yet it never works properly. I'm still thinking of my own additions, such as removing more daemons that wouldn't break the system but would keep basic functionality for the average person, such as the App Store, safari if they use it, and importing and exporting photos and videos. My plan is to make MacOS more like Windows XP, a basic general system that you can install apps on, no antivirus, no tracking, and most importantly, something that you can surf the web on.

**Comment by ajwdd** [comment]
I like that idea a lot. There are a lot of potential solutions to improve OS performance. I'm currently in college in a class learning low-level OS development. In my free time, I'll do some research and dig into the OS install dmgs with Ghidra to see if I can view and modify it to make an installable debloated macOS. I'll keep you up to date. There are a few typos in the comments in the .sh, which ill fix after class today.

**Comment by levi-chavez** [comment]
Alright, sounds good! 👍🏽

**Pull request merged**
